CHESS_BOARD_TOTAL_CELLS = 8
CHESS_BOARD_CELL_PIXELS = 80
CHESS_BOARD_PADDING = 80
CHESS_HORSE_PIXELS = 80
CHESS_BOARD_SIZE = CHESS_BOARD_CELL_PIXELS * CHESS_BOARD_TOTAL_CELLS + CHESS_BOARD_PADDING * 2 
CHESS_HORSE_START_COLOR = (240, 80, 80)
CHESS_HORSE_TARGET_COLOR = (80, 80, 240)
CHESS_BOARD_IMAGE_PIXELS = CHESS_BOARD_CELL_PIXELS * CHESS_BOARD_TOTAL_CELLS + CHESS_BOARD_CELL_PIXELS * 2 
CHESS_BOARD_IMAGE_NAME = "./images/horses.png"

PAWN_GENERAL_MOVE = 0


EMPTY = '00'
KING = 'k'
QUEEN = 'q'
BISHOP = 'b'
KNIGHT = 'n'
ROOK = 'r'
PAWN = 'w'

WHITE = '['
BLACK = ']'