CHESS_NUM_CELLS = 8
CHESS_BOARD_CELL_PIXELS = 80
CHESS_BOARD_PADDING = 80
CHESS_PIECE_PIXELS = 80
CHES_BOARD_SIZE = CHESS_BOARD_CELL_PIXELS * CHESS_NUM_CELLS + CHESS_BOARD_PADDING * 2
CHESS_PIECE_IMAGE_NAME = "./images/pieces.png"
CHESS_PIECE_SRC_COLOR = (240, 80, 80)
CHESS_PIECE_TARGET_COLOR = (80, 80, 240)

EMPTY = '00'
KING = 'k'
QUEEN = 'q'
BISHOP = 'b'
KNIGHT = 'n'
ROOK = 'r'
PAWN = 'w'

BLACK = '['
WHITE = ']'