CHESS_NUM_CELLS = 8
CHESS_BOARD_CELL_PIXELS = 80
CHESS_BOARD_PADDING = 80
CHESS_PIECE_PIXELS = 80
CHES_BOARD_SIZE = CHESS_BOARD_CELL_PIXELS * CHESS_NUM_CELLS + CHESS_BOARD_PADDING * 2
CHESS_PIECE_IMAGE_NAME = "./images/pieces.png"
CHESS_PIECE_SRC_COLOR = (240, 80, 80)
CHESS_PIECE_TARGET_COLOR = (80, 80, 240)

EMPTY = '00'
KING = 'k'
QUEEN = 'q'
BISHOP = 'b'
KNIGHT = 'n'
ROOK = 'r'
PAWN = 'w'

BLACK = '['
WHITE = ']'
        
NUM_NO_PIECE = -1
NUM_PAWN_PIECE_1 = 0
NUM_PAWN_PIECE_2 = 1
NUM_PAWN_PIECE_3 = 2
NUM_PAWN_PIECE_4 = 3
NUM_PAWN_PIECE_5 = 4
NUM_PAWN_PIECE_6 = 5
NUM_PAWN_PIECE_7 = 6
NUM_PAWN_PIECE_8 = 7
NUM_ROOK_PIECE_1 = 8
NUM_KNIGHT_PIECE_1 = 9
NUM_BISHOP_PIECE_1 = 10
NUM_KING_PIECE = 11
NUM_QUEEN_PIECE = 12
NUM_BISHOP_PIECE_2 = 13
NUM_KNIGHT_PIECE_2 = 14
NUM_ROOK_PIECE_2 = 15

