CHESS_BOARD_CELL_WIDTH = 8
CHESS_BOARD_CELL_PIXELS = 80
CHESS_BOARD_PADDING = 80
CHESS_HORSE_PIXELS = 80
CHES_BOARD_SIZE = CHESS_BOARD_CELL_PIXELS * CHESS_BOARD_CELL_WIDTH + CHESS_BOARD_PADDING * 2
CHESS_HORSE_IMAGE_NAME = "./images/horses.png"
CHESS_HORSE_SRC_COLOR = (240, 80, 80)
CHESS_HORSE_TARGET_COLOR = (80, 80, 240)

EMPTY = '00'
KING = 'k'
QUEEN = 'q'
BISHOP = 'b'
KNIGHT = 'n'
ROOK = 'r'
PAWN = 'w'

BLACK = '['
WHITE = ']'